name: build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          cache-cleanup: always

      - name: Gradle build
        run: ./gradlew build

      - name: Get latest release tag
        id: get_tag
        run: |
          latest_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' || echo "v1.0")
          echo "Latest tag: $latest_tag"
          base=${latest_tag%.*}
          minor=${latest_tag##*.}
          if [[ "$latest_tag" == "v1.0" && "$minor" == "0" ]]; then
            next_tag="v1.0"
          else
            next_tag="${base}.$((minor+1))"
          fi
          echo "next_tag=$next_tag" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ env.next_tag }}"
          tag_name: ${{ env.next_tag }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
